### ISSUE TITLE
Update flags for Table 1.3.14

### ISSUE THREAD

**Issue by Chris-Papaioannou** [david-aspital/Visum-TAG-Databook#2]
currently flagged LGV all, but should be Non-Electric, I also looked to see if this would change with year as electric fleet size increases, and it doesn't implying initial assumption this is non-electric is correct

**Comment by david-aspital** [comment]
Fixed in linked commit - closing

**Comment by Chris-Papaioannou** [comment]
Processing should run fine now but not tested, only conceivable thing I can think of that wouldn't work is difference in capitalisation. Currently looking to match against 'Non-Electric'
