### ISSUE TITLE
Standardize notation

### ISSUE THREAD

**Issue by david-aspital** [david-aspital/Visum-TAG-Databook#8]
We should have a dictionary at the top of the script that is used to standardise all notation, ie between (non-work and other, cars and car, average and all)

@Chris-Papaioannou - let's compile a list in the comments of all instances as and when we come across them. 

cars -> car
Commute & Other -> Non-Work  _**CP edit**_
average -> all

We should also have a standard (I suggest title case, with no hyphens) for multiple word variables 

_**CP edit - Capitalise Each Word, Maintain Hyphens?**_

**Comment by david-aspital** [comment]
Work (freight) -> Work
Working -> Work

**Comment by Chris-Papaioannou** [comment]
I am editing the issue here to reflect that non-work =/= other...

non-work should not go to other (as other excludes commute)
but "Commuting & Other" should go to "Non-Work" to be consistent with elsewhere

**Comment by david-aspital** [comment]
- Make A1.3.12 / A1.3.13 "Car" instead of "Cars" to make consistent with A1.3.14 / A1.3.15  - Done already
- Remove trailing spaces from strings in Table 1.3.5 - Done
- Clean up journey purpose in Table A1.3.5 - Done

**Comment by david-aspital** [comment]
Added stripping of whitespace for all string columns and change to title case (maintaining hypens) - all in linked commit
